### ISSUE TITLE
IEEE functions used in constant expressions in ieee_8.f90

### ISSUE THREAD

**Issue by nncarlson** [nncarlson/gfortran.dg#22] opened 2018-02-13 14:57 UTC
Thought this was a NAG bug, but they bounced this back to me.  Technical corrigendum 4 to the 2008 standard corrected  IEEE_SUPPORT_HALTING, IEEE_SUPPORT_FLAG, and IEEE_SUPPORT_ROUNDING from inquiry functions (okay for constant expressions) to transformational functions, which cannot be used in constant expressions.  Note that this is reflected in the 2018 draft standard document too.  So this bit of `ieee_8.f90` is not conforming:
```fortran
  logical, parameter :: l1 = ieee_support_halting(ieee_overflow)
  logical, parameter :: l2 = ieee_support_flag(ieee_overflow)
  logical, parameter :: l3 = ieee_support_flag(ieee_overflow, 0.)
  logical, parameter :: l4 = ieee_support_rounding(ieee_to_zero)
  logical, parameter :: l5 = ieee_support_rounding(ieee_to_zero, 0.d0)
  logical, parameter :: l6 = xxx(ieee_to_zero, 0.d0)
  logical, parameter :: l7 = yyy(ieee_to_zero, 0.d0)
```
Note that `xxx` and `yyy` are renames of those functions.

**Comment by janusw** [comment] 2018-02-13 15:01
duplicate of #21!

**Closed by janusw** 2018-02-13 15:01 UTC

**Comment by nncarlson** [comment] 2018-02-13 15:03
Ha!  I should have looked to see what activity happened overnight :)

**Comment by nncarlson** [comment] 2018-02-13 15:08
I mistook Themos' email as direct correspondence (I fed my NAG bugs to him directly), but it was coming from github.
